// ==UserScript==
// @name         Your Hack Name.....
// @version      1.1
// @description  Your description.....
// @author       Your name......
// @match        https://example.com
// @grant        none
// ==/UserScript==
